import Head from "next/head";
import Layout from "~/components/hoc/Layout";
import Task from "~/components/ui/Task";
import Timer from "~/components/ui/Timer";
import TitleQuizz from "~/components/ui/TitleQuizz";

export default function Home() {
  return (
    <>
      <Head>
        <title>Quizz Country</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <Layout>
        <main className="p-2">
          <div className="flex items-center justify-between">
            <TitleQuizz />
            <Timer />
          </div>
          <Task />
        </main>
      </Layout>
    </>
  );
}
